sudo: required
language: android


before_install:
  - yes | sdkmanager "platforms;android-28"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.android/build-cache

env:
  - TEST_MATRIX=assemble
  - TEST_MATRIX=units

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28

script:
  - if [ $TEST_MATRIX == "assemble" ]; then ./scripts/ci_assemble.sh; fi
  - if [ $TEST_MATRIX == "units" ]; then ./scripts/ci_unit_test.sh; fi

after_success:
  - if [ $TEST_MATRIX != "assemble" ]; then bash <(curl -s https://codecov.io/bash); fi
