package kin.sendkin.events;

public enum SendKinPages {
    CHOOSE_ADDRESS,
    SET_AMOUNT,
    CONFIRM_POPUP,
    SENDING_POPUP,
    SUCCESS_POPUP,
    FAIL_POPUP,
    TIMEOUT_POPUP,
    MY_PUBLIC_ADDRESS_POPUP,
    WHATIS_PUBLIC_ADDRESS_POPUP
}
